version: '3.5'

services:
  web:
    build:
      dockerfile: ./Dockerfile
      context: .
    environment:
      PG_HOST: pg
    container_name: task_web_app
    command: python main.py
    depends_on:
      - pg
    volumes:
      - ./web_app:/app
    ports:
      - 5000:5000
  pg:
    image: postgres:12
    environment:
      POSTGRES_DB: task-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
    - ./data/pgdata:/var/lib/postgresql/data/pgdata
#    ports:
#    - 5432:5432